# docker-compose -f docker-compose.services.yml -f docker-compose.prod.yml up -d --build
# docker-compose -f docker-compose.services.yml -f docker-compose.prod.yml down
services:
  backend:
    container_name: tellme_back
    build:
      context: .
      dockerfile: ./apps/tellme-back/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
