export enum EMAIL_AUTH {
    CONFIRM_EMAIL = "CONFIRM_EMAIL",
    EMAIL_CONFIRMED = "EMAIL_CONFIRMED",
    RESET_PASSWORD = "RESET_PASSWORD",
    PASSWORD_EDITED = "PASSWORD_EDITED",
}

export type EMAIL = EMAIL_AUTH;


export enum USER {
    CREATED = "CREATED",
    UPDATED = "UPDATED",
    DELETED = "DELETED",
}
export type EVENT_BUS_TYPE = EMAIL | USER; 